poll = read.csv("AnonymityPoll.csv")
summary(poll)
str(poll)
ncol(poll)
table(poll$Smartphone)
table(poll$State, poll$Region)
# another approach - using subset
midwestinterviewees = subset(poll, Region == "Midwest")
table(poll$Internet.Use, poll$Smartphone)
table(is.na(poll$Internet.Use))
table(is.na(poll$Smartphone))
limited = subset(poll, poll$Internet.Use == 1 | poll$Smartphone == 1)
str(limited)
summary(limited)
table(is.na(limited$Sex))
table(limited$Info.On.Internet)
mean(limited$Worry.About.Info, na.rm = TRUE)
mean(limited$Anonymity.Possible, na.rm = TRUE)
mean(limited$Tried.Masking.Identity, na.rm = TRUE)
mean(limited$Privacy.Laws.Effective, na.rm = TRUE)
hist(limited$Age)
plot(limited$Age, limited$Info.On.Internet)
max(table(limited$Age, limited$Info.On.Internet))
plot(limited$Age, limited$Info.On.Internet)
jitter(c(1,2,3))
plot(jitter(limited$Age), jitter(limited$Info.On.Internet))
tapply(limited$Info.On.Internet, limited$Smartphone, summary)

tapply(limited$Tried.Masking.Identity, limited$Smartphone, summary)

